# example file structure showing grouping. Not all groups are shown.
UPD:
  isodisomy:
    - sample_A
    - ...
  segmental_disomy:
    - ...
    - ...
  heterodisomy_or_ICepimutation:
    - C
    - ...
    - ...
  atypical:
    - ...
    - ...
deletions:
  TypeI_classic:
    - ...
    - ...
  TypeI_complex:
    - ...
    - ...
  TypeII_classic:
    - ...
    - ...
  TypeII_complex:
    - ...
    - ...
  atypical_del:
    - ...
    - ...
  IC_deletion:
    - ...
    - ...
deletions_cov_part2:
  TypeII_classic:
    - ...
    - ...
